language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=2.4
  matrix:
    - TAG=2.4 HTTPD_VER=2.4.29 EXTRA_TAG=2

script:
  - make && make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"